apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-proxy-deployment
  namespace: default
  labels:
    app: internal-proxy
spec:
  selector:
    matchLabels:
      app: internal-proxy
  template:
    metadata:
      labels:
        app: internal-proxy
    spec:
      containers:
        - name: internal-api
          image: madhuakula/k8s-goat-internal-api
          imagePullPolicy: IfNotPresent
          command: ["node"]
          args: ["server.js", "0.0.0.0"]
          resources:
            limits:
              cpu: 50m
              memory: 60Mi
          ports:
            - containerPort: 3000 # 对应内网 API 服务
        - name: info-app
          image: madhuakula/k8s-goat-info-app
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 30m
              memory: 50Mi
          ports:
            - containerPort: 5000 # 对应信息展示应用
---
apiVersion: v1
kind: Service
metadata:
  name: internal-proxy-api-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: internal-proxy
  ports:
    - name: api-port
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003
