apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-goat-home-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: kubernetes-goat-home
  template:
    metadata:
      labels:
        app: kubernetes-goat-home
    spec:
      containers:
        - name: kubernetes-goat-home
          image: madhuakula/k8s-goat-home
          # 简体中文注释：修正 1 - 强制使用本地镜像
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "100Mi" # 稍微调大一点防止 OOM
              cpu: "50m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-goat-home-service
  namespace: default
spec:
  # 简体中文注释：修正 2 - 开启 NodePort 供宿主机访问
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000 # 必须对应 kind-config.yaml 里的 containerPort
  selector:
    app: kubernetes-goat-home
