apiVersion: v1
kind: Namespace
metadata:
  name: secure-middleware
---
apiVersion: v1
kind: Service
metadata:
  namespace: secure-middleware
  name: cache-store-service
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: cache-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: secure-middleware
  name: cache-store-deployment
  labels:
    app: cache-store
spec:
  selector:
    matchLabels:
      app: cache-store
  template:
    metadata:
      labels:
        app: cache-store
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node01
      containers:
        - name: cache-store
          image: madhuakula/k8s-goat-cache-store
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
