apiVersion: batch/v1
kind: Job
metadata:
  name: hidden-in-layers
spec:
  template:
    metadata:
      name: hidden-in-layers
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: k8s-node01
      containers:
        - name: hidden-in-layers
          image: madhuakula/k8s-goat-hidden-in-layers
          imagePullPolicy: IfNotPresent
          # command:
          #  - "bin/sh"
          #  - "-c"
          #  - "htop"
      restartPolicy: Never
