apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metadata-db.fullname" . }}
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata-db.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "metadata-db.name" . }}
    helm.sh/chart: {{ include "metadata-db.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      {{- if and .Values.service.nodePort (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "metadata-db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
```