apiVersion: v1
kind: Service
metadata:
  name: batch-check-service
spec:
  type: NodePort
  selector:
    app: batch-check
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
